version: '3'
services:
  Squid:
    image: sameersbn/squid:latest
    container_name: squid
    ports:
      - "3128:3128"
    volumes:
      - /srv/docker/squid/cache:/var/spool/squid
      - /home/madongo/docker-squid/squid.conf:/etc/squid/squid.conf  
    restart: always
